require "yaml"
settings = YAML.load_file "settings.yaml"

Vagrant.configure("2") do |config|
  config.vm.box = settings["software"]["box"]

  config.vm.box_check_update = true

  config.vm.define settings["host"]["hostname"] do |host|
    host.vm.hostname = settings["host"]["hostname"]
    host.vm.provider "virtualbox" do |vb|
      vb.cpus = settings["host"]["cpu"]
      vb.memory = settings["host"]["memory"]
    end

    host.vm.provision "shell", path: "scripts/#{host.vm.hostname}.sh"
  end
end
